const menu = function(){

  let ul = document.createElement('ul');
  let li1 = document.createElement('li');
  let li2 = document.createElement('li');
  let li3 = document.createElement('li');
  let li4 = document.createElement('li');
  ul.style.width = "100%";
  ul.style.height = "100px";
  ul.style.position = "fixed";
  ul.style.background = "black";
  ul.style.margin = "0px";
  ul.style.listStyle = "none";
  ul.style.display = "flex";
  ul.style.justifyContent = "space-around";
  ul.style.flexDirection = "row";
  ul.style.alignItems = "center";
  /*Links*/
  let a1 = document.createElement('a');
  let a2 = document.createElement('a');
  let a3 = document.createElement('a');
  let a4 = document.createElement('a');
  a1.setAttribute("href", "./index2.js");
  a2.setAttribute("href", "#");
  a3.setAttribute("href", "#");
  a4.setAttribute("href", "#");
  a1.style.textDecoration = "none";
  a2.style.textDecoration = "none";
  a3.style.textDecoration = "none";
  a4.style.textDecoration = "none";
  a1.innerHTML = "JavaScript";
  a2.innerHTML = "Python";
  a3.innerHTML = "Java";
  a4.innerHTML = "C#";
  a1.style.color = "white";
  a2.style.color = "white";
  a3.style.color = "white";
  a4.style.color = "white";
  li1.appendChild(a1);
  li2.appendChild(a2);
  li3.appendChild(a3);
  li4.appendChild(a4);
  ul.appendChild(li1);
  ul.appendChild(li2);
  ul.appendChild(li3);
  ul.appendChild(li4);
  document.querySelector('body header').appendChild(ul);
}();
menu();
